class CountryData {
  final String name;
  final String code;
  final String dialCode;
  final int minLength;
  final int maxLength;

  const CountryData({
    required this.name,
    required this.code,
    required this.dialCode,
    required this.minLength,
    required this.maxLength,
  });

  static List<CountryData> countries = const [
    CountryData(
        name: "Afghanistan",
        code: "AF",
        dialCode: "+93",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Albania",
        code: "AL",
        dialCode: "+355",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Algeria",
        code: "DZ",
        dialCode: "+213",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Andorra",
        code: "AD",
        dialCode: "+376",
        minLength: 6,
        maxLength: 6),
    CountryData(
        name: "Angola",
        code: "AO",
        dialCode: "+244",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Argentina",
        code: "AR",
        dialCode: "+54",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Armenia",
        code: "AM",
        dialCode: "+374",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Australia",
        code: "AU",
        dialCode: "+61",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Austria",
        code: "AT",
        dialCode: "+43",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Azerbaijan",
        code: "AZ",
        dialCode: "+994",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Bahamas",
        code: "BS",
        dialCode: "+1242",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Bahrain",
        code: "BH",
        dialCode: "+973",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Bangladesh",
        code: "BD",
        dialCode: "+880",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Barbados",
        code: "BB",
        dialCode: "+1246",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Belarus",
        code: "BY",
        dialCode: "+375",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Belgium",
        code: "BE",
        dialCode: "+32",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Belize",
        code: "BZ",
        dialCode: "+501",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Benin",
        code: "BJ",
        dialCode: "+229",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Bhutan",
        code: "BT",
        dialCode: "+975",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Bolivia",
        code: "BO",
        dialCode: "+591",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Bosnia and Herzegovina",
        code: "BA",
        dialCode: "+387",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Botswana",
        code: "BW",
        dialCode: "+267",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Brazil",
        code: "BR",
        dialCode: "+55",
        minLength: 10,
        maxLength: 11),
    CountryData(
        name: "Brunei",
        code: "BN",
        dialCode: "+673",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Bulgaria",
        code: "BG",
        dialCode: "+359",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Burkina Faso",
        code: "BF",
        dialCode: "+226",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Burundi",
        code: "BI",
        dialCode: "+257",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Cambodia",
        code: "KH",
        dialCode: "+855",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Cameroon",
        code: "CM",
        dialCode: "+237",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Canada",
        code: "CA",
        dialCode: "+1",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Cape Verde",
        code: "CV",
        dialCode: "+238",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Central African Republic",
        code: "CF",
        dialCode: "+236",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Chad", code: "TD", dialCode: "+235", minLength: 8, maxLength: 8),
    CountryData(
        name: "Chile", code: "CL", dialCode: "+56", minLength: 9, maxLength: 9),
    CountryData(
        name: "China",
        code: "CN",
        dialCode: "+86",
        minLength: 11,
        maxLength: 11),
    CountryData(
        name: "Colombia",
        code: "CO",
        dialCode: "+57",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Comoros",
        code: "KM",
        dialCode: "+269",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Congo",
        code: "CG",
        dialCode: "+242",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Costa Rica",
        code: "CR",
        dialCode: "+506",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Croatia",
        code: "HR",
        dialCode: "+385",
        minLength: 8,
        maxLength: 9),
    CountryData(
        name: "Cuba", code: "CU", dialCode: "+53", minLength: 8, maxLength: 8),
    CountryData(
        name: "Cyprus",
        code: "CY",
        dialCode: "+357",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Czech Republic",
        code: "CZ",
        dialCode: "+420",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Denmark",
        code: "DK",
        dialCode: "+45",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Djibouti",
        code: "DJ",
        dialCode: "+253",
        minLength: 6,
        maxLength: 6),
    CountryData(
        name: "Dominica",
        code: "DM",
        dialCode: "+1767",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Dominican Republic",
        code: "DO",
        dialCode: "+1",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Ecuador",
        code: "EC",
        dialCode: "+593",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Egypt",
        code: "EG",
        dialCode: "+20",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "El Salvador",
        code: "SV",
        dialCode: "+503",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Equatorial Guinea",
        code: "GQ",
        dialCode: "+240",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Eritrea",
        code: "ER",
        dialCode: "+291",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Estonia",
        code: "EE",
        dialCode: "+372",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Eswatini",
        code: "SZ",
        dialCode: "+268",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Ethiopia",
        code: "ET",
        dialCode: "+251",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Fiji", code: "FJ", dialCode: "+679", minLength: 7, maxLength: 7),
    CountryData(
        name: "Finland",
        code: "FI",
        dialCode: "+358",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "France",
        code: "FR",
        dialCode: "+33",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Gabon",
        code: "GA",
        dialCode: "+241",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Gambia",
        code: "GM",
        dialCode: "+220",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Georgia",
        code: "GE",
        dialCode: "+995",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Germany",
        code: "DE",
        dialCode: "+49",
        minLength: 10,
        maxLength: 11),
    CountryData(
        name: "Ghana",
        code: "GH",
        dialCode: "+233",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Greece",
        code: "GR",
        dialCode: "+30",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Grenada",
        code: "GD",
        dialCode: "+1473",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Guatemala",
        code: "GT",
        dialCode: "+502",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Guinea",
        code: "GN",
        dialCode: "+224",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Guinea-Bissau",
        code: "GW",
        dialCode: "+245",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Guyana",
        code: "GY",
        dialCode: "+592",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Haiti",
        code: "HT",
        dialCode: "+509",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Honduras",
        code: "HN",
        dialCode: "+504",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Hungary",
        code: "HU",
        dialCode: "+36",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Iceland",
        code: "IS",
        dialCode: "+354",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "India",
        code: "IN",
        dialCode: "+91",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Indonesia",
        code: "ID",
        dialCode: "+62",
        minLength: 10,
        maxLength: 13),
    CountryData(
        name: "Iran",
        code: "IR",
        dialCode: "+98",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Iraq",
        code: "IQ",
        dialCode: "+964",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Ireland",
        code: "IE",
        dialCode: "+353",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Israel",
        code: "IL",
        dialCode: "+972",
        minLength: 9,
        maxLength: 10),
    CountryData(
        name: "Italy",
        code: "IT",
        dialCode: "+39",
        minLength: 9,
        maxLength: 10),
    CountryData(
        name: "Jamaica",
        code: "JM",
        dialCode: "+1876",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Japan",
        code: "JP",
        dialCode: "+81",
        minLength: 10,
        maxLength: 11),
    CountryData(
        name: "Jordan",
        code: "JO",
        dialCode: "+962",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Kazakhstan",
        code: "KZ",
        dialCode: "+7",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Kenya",
        code: "KE",
        dialCode: "+254",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Kiribati",
        code: "KI",
        dialCode: "+686",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Kuwait",
        code: "KW",
        dialCode: "+965",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Kyrgyzstan",
        code: "KG",
        dialCode: "+996",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Laos",
        code: "LA",
        dialCode: "+856",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Latvia",
        code: "LV",
        dialCode: "+371",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Lebanon",
        code: "LB",
        dialCode: "+961",
        minLength: 7,
        maxLength: 8),
    CountryData(
        name: "Lesotho",
        code: "LS",
        dialCode: "+266",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Liberia",
        code: "LR",
        dialCode: "+231",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Libya",
        code: "LY",
        dialCode: "+218",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Liechtenstein",
        code: "LI",
        dialCode: "+423",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Lithuania",
        code: "LT",
        dialCode: "+370",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Luxembourg",
        code: "LU",
        dialCode: "+352",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Madagascar",
        code: "MG",
        dialCode: "+261",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Malawi",
        code: "MW",
        dialCode: "+265",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Malaysia",
        code: "MY",
        dialCode: "+60",
        minLength: 9,
        maxLength: 10),
    CountryData(
        name: "Maldives",
        code: "MV",
        dialCode: "+960",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Mali", code: "ML", dialCode: "+223", minLength: 8, maxLength: 8),
    CountryData(
        name: "Malta",
        code: "MT",
        dialCode: "+356",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Marshall Islands",
        code: "MH",
        dialCode: "+692",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Mauritania",
        code: "MR",
        dialCode: "+222",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Mauritius",
        code: "MU",
        dialCode: "+230",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Mexico",
        code: "MX",
        dialCode: "+52",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Micronesia",
        code: "FM",
        dialCode: "+691",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Moldova",
        code: "MD",
        dialCode: "+373",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Monaco",
        code: "MC",
        dialCode: "+377",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Mongolia",
        code: "MN",
        dialCode: "+976",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Montenegro",
        code: "ME",
        dialCode: "+382",
        minLength: 8,
        maxLength: 9),
    CountryData(
        name: "Morocco",
        code: "MA",
        dialCode: "+212",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Mozambique",
        code: "MZ",
        dialCode: "+258",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Myanmar",
        code: "MM",
        dialCode: "+95",
        minLength: 8,
        maxLength: 9),
    CountryData(
        name: "Namibia",
        code: "NA",
        dialCode: "+264",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Nauru",
        code: "NR",
        dialCode: "+674",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Nepal",
        code: "NP",
        dialCode: "+977",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Netherlands",
        code: "NL",
        dialCode: "+31",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "New Zealand",
        code: "NZ",
        dialCode: "+64",
        minLength: 8,
        maxLength: 10),
    CountryData(
        name: "Nicaragua",
        code: "NI",
        dialCode: "+505",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Niger",
        code: "NE",
        dialCode: "+227",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Nigeria",
        code: "NG",
        dialCode: "+234",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "North Korea",
        code: "KP",
        dialCode: "+850",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "North Macedonia",
        code: "MK",
        dialCode: "+389",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Norway",
        code: "NO",
        dialCode: "+47",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Oman", code: "OM", dialCode: "+968", minLength: 8, maxLength: 8),
    CountryData(
        name: "Pakistan",
        code: "PK",
        dialCode: "+92",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Palau",
        code: "PW",
        dialCode: "+680",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Panama",
        code: "PA",
        dialCode: "+507",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Papua New Guinea",
        code: "PG",
        dialCode: "+675",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Paraguay",
        code: "PY",
        dialCode: "+595",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Peru", code: "PE", dialCode: "+51", minLength: 9, maxLength: 9),
    CountryData(
        name: "Philippines",
        code: "PH",
        dialCode: "+63",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Poland",
        code: "PL",
        dialCode: "+48",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Portugal",
        code: "PT",
        dialCode: "+351",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Qatar",
        code: "QA",
        dialCode: "+974",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Romania",
        code: "RO",
        dialCode: "+40",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Russia",
        code: "RU",
        dialCode: "+7",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Rwanda",
        code: "RW",
        dialCode: "+250",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Saint Kitts and Nevis",
        code: "KN",
        dialCode: "+1869",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Saint Lucia",
        code: "LC",
        dialCode: "+1758",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Saint Vincent and the Grenadines",
        code: "VC",
        dialCode: "+1784",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Samoa",
        code: "WS",
        dialCode: "+685",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "San Marino",
        code: "SM",
        dialCode: "+378",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Sao Tome and Principe",
        code: "ST",
        dialCode: "+239",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Saudi Arabia",
        code: "SA",
        dialCode: "+966",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Senegal",
        code: "SN",
        dialCode: "+221",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Serbia",
        code: "RS",
        dialCode: "+381",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Seychelles",
        code: "SC",
        dialCode: "+248",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Sierra Leone",
        code: "SL",
        dialCode: "+232",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Singapore",
        code: "SG",
        dialCode: "+65",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Slovakia",
        code: "SK",
        dialCode: "+421",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Slovenia",
        code: "SI",
        dialCode: "+386",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Solomon Islands",
        code: "SB",
        dialCode: "+677",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Somalia",
        code: "SO",
        dialCode: "+252",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "South Africa",
        code: "ZA",
        dialCode: "+27",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "South Korea",
        code: "KR",
        dialCode: "+82",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "South Sudan",
        code: "SS",
        dialCode: "+211",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Spain", code: "ES", dialCode: "+34", minLength: 9, maxLength: 9),
    CountryData(
        name: "Sri Lanka",
        code: "LK",
        dialCode: "+94",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Sudan",
        code: "SD",
        dialCode: "+249",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Suriname",
        code: "SR",
        dialCode: "+597",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Sweden",
        code: "SE",
        dialCode: "+46",
        minLength: 7,
        maxLength: 13),
    CountryData(
        name: "Switzerland",
        code: "CH",
        dialCode: "+41",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Syria",
        code: "SY",
        dialCode: "+963",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Taiwan",
        code: "TW",
        dialCode: "+886",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Tajikistan",
        code: "TJ",
        dialCode: "+992",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Tanzania",
        code: "TZ",
        dialCode: "+255",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Thailand",
        code: "TH",
        dialCode: "+66",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Togo", code: "TG", dialCode: "+228", minLength: 8, maxLength: 8),
    CountryData(
        name: "Tonga",
        code: "TO",
        dialCode: "+676",
        minLength: 5,
        maxLength: 5),
    CountryData(
        name: "Trinidad and Tobago",
        code: "TT",
        dialCode: "+1868",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Tunisia",
        code: "TN",
        dialCode: "+216",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Turkey",
        code: "TR",
        dialCode: "+90",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Turkmenistan",
        code: "TM",
        dialCode: "+993",
        minLength: 8,
        maxLength: 8),
    CountryData(
        name: "Tuvalu",
        code: "TV",
        dialCode: "+688",
        minLength: 5,
        maxLength: 5),
    CountryData(
        name: "Uganda",
        code: "UG",
        dialCode: "+256",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Ukraine",
        code: "UA",
        dialCode: "+380",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "United Arab Emirates",
        code: "AE",
        dialCode: "+971",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "United Kingdom",
        code: "GB",
        dialCode: "+44",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "United States",
        code: "US",
        dialCode: "+1",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Uruguay",
        code: "UY",
        dialCode: "+598",
        minLength: 8,
        maxLength: 9),
    CountryData(
        name: "Uzbekistan",
        code: "UZ",
        dialCode: "+998",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Vanuatu",
        code: "VU",
        dialCode: "+678",
        minLength: 7,
        maxLength: 7),
    CountryData(
        name: "Vatican City",
        code: "VA",
        dialCode: "+379",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Venezuela",
        code: "VE",
        dialCode: "+58",
        minLength: 10,
        maxLength: 10),
    CountryData(
        name: "Vietnam",
        code: "VN",
        dialCode: "+84",
        minLength: 9,
        maxLength: 10),
    CountryData(
        name: "Yemen",
        code: "YE",
        dialCode: "+967",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Zambia",
        code: "ZM",
        dialCode: "+260",
        minLength: 9,
        maxLength: 9),
    CountryData(
        name: "Zimbabwe",
        code: "ZW",
        dialCode: "+263",
        minLength: 9,
        maxLength: 9),
  ];
}
