// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNWXTqeyNqPVup8eDx8yQEQ6mhn9yiUVc',
    appId: '1:108167851161:web:28d653067451fddfbc9c08',
    messagingSenderId: '108167851161',
    projectId: 'cat-gallery-e6567',
    authDomain: 'cat-gallery-e6567.firebaseapp.com',
    storageBucket: 'cat-gallery-e6567.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn2TWqBDsbQf7Ti_WiJq2l8MK1Z5GROtQ',
    appId: '1:108167851161:android:d6ae24d62e0afabbbc9c08',
    messagingSenderId: '108167851161',
    projectId: 'cat-gallery-e6567',
    storageBucket: 'cat-gallery-e6567.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiGLee00BksF-WKJ7j6YLm0qUTr9BSGxA',
    appId: '1:108167851161:ios:9fb7dd4abc377399bc9c08',
    messagingSenderId: '108167851161',
    projectId: 'cat-gallery-e6567',
    storageBucket: 'cat-gallery-e6567.appspot.com',
    iosBundleId: 'com.example.myCat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiGLee00BksF-WKJ7j6YLm0qUTr9BSGxA',
    appId: '1:108167851161:ios:9fb7dd4abc377399bc9c08',
    messagingSenderId: '108167851161',
    projectId: 'cat-gallery-e6567',
    storageBucket: 'cat-gallery-e6567.appspot.com',
    iosBundleId: 'com.example.myCat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNWXTqeyNqPVup8eDx8yQEQ6mhn9yiUVc',
    appId: '1:108167851161:web:12027c3142ed3387bc9c08',
    messagingSenderId: '108167851161',
    projectId: 'cat-gallery-e6567',
    authDomain: 'cat-gallery-e6567.firebaseapp.com',
    storageBucket: 'cat-gallery-e6567.appspot.com',
  );
}
